- CONTRIBUTING.md
- README.md
- ships/README.md
- ships/guidelines/ship-template.md
- Moving and codifying the enhancement proposal process in
shipwright-io/build so that it can be shared across all Shipwright
projects.
- Relevant community documentaiton updated with links to the SHIP
guidelines.
- Removed references to OKD and simplified the ship template.
> SHIP Proposal Process

- ships/0004-build-env-vars.md
This proposal introduces the concept of build strategy overrides,
whereby a developer can override the behavior declared in a build
strategy. Augmenting the environment variables in a build step is
presented as the first type of override that is made available.
The proposal includes rules and behavior for environment variables that
are declared in a build strategy. Specifically, builds cannot overwrite
declared environment variables unless said env var is exposed as a build
parameter.
> SHIP-0004: Build Environment Variables

- ships/0007-package-manager-releases.md
_TL;DR_: 
> Users of CLI tools are accustomed to the usage of package managers to install a tool and to keep it up-to-date. The `shp` CLI tool should have an option to be installed with such a package manager.
> SHIP-0007: Release Shipwright CLI through Package Managers

- ships/0016-enable-local-source-code-support.md
Explain removal of `pruneBuild`.
Correct field names with the actual ones being used in the implementation.
Update example CLI calls.
Fix Markdown linter issues.
> Update local source SHIP

- ships/0024-surfacing-errors-to-buildrun.md
This ship proposes introducing error messages from low-level resources like TaskRuns into BuildRuns. So that users can better understand the underlying issues and third-party applications have an API to consume them.
> SHIP-0024: Surfacing Errors to BuildRuns

- ships/0022-build-strategy-volumes.md
This proposal will allow build strategy authors to declare volumes which
can be shared across build steps and build runs. The build strategy will
declare the mount point for the volume in each build step.
Volumes can either have a fixed volume source, or an
overridable volume source that can be set in a `Build` or `BuildRun`.
Volumes declared in a build strategy are translated into the following:
1. Volume mounts for each task step that have a corresponding build step
2. A volume that is added to the TaskRun's pod template
This feature will replace the implict creation of emptyDir volumes in build
strategies. Build strategies will need to explicitly declare emptyDir
volumes moving forward.
> SHIP-0022: Build Strategy Volumes

- ships/0025-strategy-parameters-enhancements.md
This ship enhances the build strategy parameters support by three features:
- array parameters
- values from Secrets
- values from ConfigMaps
> SHIP-0025: Add ship to support array strategy parameters and secret and configmap key references as value

- ships/0027-image-abstraction-layer.md
Proposal for a Kubernetes Image Abstraction Layer similar to OpenShift's
ImageStreams.
> SHIP-0027: Image Abstraction Layer

- ships/0026-shipwright-managed-push.md
This ship describes why and how we provide means for build strategies to store the produced container image as a tarball in ephemeral storage instead of doing the image push. The push will then be performed by a shipwright-managed step.
> SHIP-0026: Introduce shipwright-managed push

- ships/0029-one-off-builds.md
Ref: https://github.com/shipwright-io/build/pull/1016
Unify indentation in YAML examples.
Fix missing pointer in `BuildRunSpec` struct.
> Update one-off build SHIP

- ships/0036-runAs-for-supporting-steps.md
The proposal explains the background on why we currently have a prepare step that runs as root in some sample build strategies and aims to get rid of them by running all steps (shipwright-injected and strategy steps) as the same user.
> SHIP-0036: Proposal to set runAs user/group for supporting steps to the runAs configuration of the build strategy steps

- ships/0037-build-output-timestamp.md
Add SHIP to propose the introduction of output image timestamp processing.
>  SHIP-0037: Use build output timestamps

- ships/0037-build-output-timestamp.md
Add `BuildTimestamp` to define that the image timestamp should be set to the timestamp of the current Build Run.
```release-note
NONE
```
> Amend 0037 with `BuildTimestamp`

- ships/0038-release-branching-backports.md
Provisional enhancement proposal to outline Shipwright's strategy for release branching and applying backports. The proposal's goal is to let sub-projects issue patch releases for bug fixes and security advisories. This is accomplished using a release branch name convention and updates to project release processes.
Future iterations of this proposal will identify specific changes to be made in our existing release tooling. These updates will also describe how to apply these procedures retroactively to the `v0.12.0` releases of the following sub-projects:
- build
- operator
- cli
```release-note
NONE
```
> SHIP-0038: Release Branching and Backports

- ships/0038-release-branching-backports.md
This updates SHIP-0038 with sufficient details to mark it "implementable." The proposal now contains specific details on how to use starter and reusable GitHub Action workflows to implement release branching across all component repos. Security requirements such as branch protection are fully outlined, and a process for backporting using the Prow cherrypick bot is described.
This proposal attempts to minimize changes to existing release workflows. Adopting a more uniform toolkit like GoReleaser would add scope and discourage future attempts to "dogfood" Shipwright. Ideally Shipwright is able to build and release itself, however this imposes real infrastructure costs the project is not able to fund at present.
Other alternatives are articulated in the proposal as well.
Related to #85. …
> SHIP-0038: Implementable Version

- ships/0037-build-output-timestamp.md
Add missing `BuildTimestamp` in example.
```release-note
NONE
```
> Update output timestamp SHIP

- ships/0039-build-scheduler-opts.md
~Provisional~ _**Implementable**_ proposal to add API options to control where build pods are scheduled. These will rely on core Kubernetes features related to pod scheduling.
This proposal was partially motivated by the multi-arch feature discussions, where it was revealed that we currently have no means of controlling where build pods are scheduled. While these features may support a future proof of concept for multi-arch builds, orchestrating multi-arch builds end to end is out of scope.
```release-note
NONE
```
> SHIP-0039: Build Scheduler Options

- MAINTAINERS.md
Related to https://github.com/shipwright-io/community/issues/240
This document is based on https://contribute.cncf.io/maintainers/templates/maintainers/ . Although we have not yet defined roles, I'm adding in the list the `admin and maintainer`. Once we define the governance doc, I expect those two roles to be there, per [Github Roles and Responsabilities](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization#repository-access-for-each-permission-level)
```release-note
NONE
```
> ADD MAINTAINERS file

- README.md
fix: update community meetings calendar link to https://zoom-lfx.platform.linuxfoundation.org/meetings/shipwright
> fix: update community meetings calendar link

- README.md
This community README update serves as an announcement that any community member can receive automated notifications of Shipwright activity through GitHub's webhook feed mechanism. For now, anyone can request access by emailing the project admins
(shipwright-admins@lists.cncf.io). Maintainers with org-wide write permission will then need to work with the requestor to obtain the desired endpoint, webhook secret, payload format, and types of events to receive. In the future, we can gather some of this information up front through a GitHub issue template (obviously not the secret - that should be exchanged through a proper private channel).
This was prompted by previous work I did to send GitHub issue and PR events to Fedora's GitHub2FedMsg bus [1]. I had set this up on behalf of Red Hat to …
> doc: Shipwright Webhook Feed

- GOVERNANCE.md
Adding an official governance document, based on the CNCF "Maintainer Council" template. Shipwright has had a de-facto maintainer council since its inception; this document formalizes what has otherwise been a verbal agreement amongst the founder-maintainers. This change ensures the project has a clear path for new maintainers to join the project, and outlines maintainer responsibilities once accepted.
Fixes #243 
/kind feature
```release-note
Adopt "Maintainer Council" governance charter
```
> feat: Adopt Maintainer Council Governance
